#pragma once
#include <vector>
#include <string>

// Actually useful bases
static const std::vector<std::string> BASE_2  = { "0","1" };
static const std::vector<std::string> BASE_8  = { "0","1","2","3","4","5","6","7"};
static const std::vector<std::string> BASE_10 = { "0","1","2","3","4","5","6","7","8","9" };
static const std::vector<std::string> BASE_64 = { "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","0","1","2","3","4","5","6","7","8","9","+","/" };

// Fun bases
static const std::vector<std::string> BASE_UWU = {
	"uwu",
	"UwU",
	"<3",
	":P",
	":p",
	":o",
	":O",
	":3",
	":)",
	"^.^",
	"^_^",
	"^^",
	"XD",
	"XDD",
	"XDDD",
	"xD",
	"xDD",
	"xDDD",
	"(*^.^*)",
	"(*^_^*)",
	"devewopa",
	"cutieee",
	"cutewr",
	"whiiiich",
	"masta",
	"mastaaaa",
	"hiiiii",
	"hewwo",
	"soopa",
	"doopa",
	"favowite",
	"kawaii",
	"rawr",
	"keewl",
	"keeeewl",
	"Owww",
	"Awww",
	"haaaai",
	"haaaay",
	"heeeey",
	"heeeei",
	"senpaiiii",
	"senpaiiiw",
	"sewnpaiii",
	"i",
	"nyeed",
	"awe",
	"youuu",
	"twe",
	"best",
	"ruff",
	"me",
	"nyeko",
	"eughh",
	"snaffle",
	"cutsie",
	"toot",
	"whiffle",
	"nappies",
	"chiffchaff",
	"kawaiisu",
	"winks",
	"boop",
	"smoochies",
	"whiffskaws",
	"chomp",
	"toesy-woesies",
	"smush",
	"snuff",
	"sniff",
	"snaff",
};

// Source: https://lakinkonieczny.wordpress.com/2012/12/06/dialogue-noises-agh-ugh-shh-and-so-much-more/
static const std::vector<std::string> BASE_UGH = {
	"Agh!",
	"Ugh",
	"Shh!",
	"Pft!",
	"Aah!",
	"Uaah!",
	"Gah!",
	"Grr...",
	"Duh!",
	"Psh!",
	"Ah...",
	"Er-",
	"Huh...?",
	"Uh-huh...",
	"Nu-uh...",
	"Bah!",
	"Wha-?"
};
